# Step 1: Use a base image for Node.js
FROM node:16 AS node-backend

# Set working directory for Node.js
WORKDIR /app

# Install Node.js dependencies
COPY backend/package.json  backend/package-lock.json ./
RUN npm ci

# Copy the rest of the backend files
COPY backend/ .

# Step 2: Set up Flask (Python)
FROM python:3.9 AS flask-backend

# Set working directory for Flask
WORKDIR /app

# Install Python dependencies
COPY backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask application code
COPY backend/ .

# Step 3: Copy .env file to container
COPY .env /app/.env

# Step 3: Expose ports for both Flask and Node.js services
EXPOSE 5000 5001

# Command to start both Flask and Node.js in one container
CMD ["sh", "-c", "npm run dev & python app.py"]
