import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const ReportPage = () => {
  const { reportId } = useParams(); // Get the reportId from the URL
  const [reportData, setReportData] = useState(null);

  useEffect(() => {
    // Fetch the report data based on reportId (e.g., from an API or local storage)
    const storedReportData = localStorage.getItem(`reportData-${reportId}`);
    
    if (storedReportData) {
      setReportData(JSON.parse(storedReportData));
    } else {
      // Handle the case where report data is not found
      console.error('Report data not found!');
    }
  }, [reportId]);

  const handleDownload = () => {
    // Generate the PDF
    const printSection = document.getElementById('print-section');
    if (printSection) {
      html2canvas(printSection).then((canvas) => {
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF();
        pdf.addImage(imgData, 'PNG', 0, 0);
        pdf.save('SkinCancerReport.pdf');
      });
    }
  };

  if (!reportData) {
    return <div>Loading...</div>; // Show loading while data is being fetched
  }

  return (
    <div className="flex flex-col justify-center items-center min-h-screen p-8 bg-gradient-to-r from-blue-50 to-blue-100">
      <div id="print-section" className="bg-white p-9 rounded-2xl shadow-lg w-full max-w-4xl space-y-6 border border-gray-200">
        <header className="mb-6 flex justify-between items-center">
          <div className="flex items-center">
            <img src="/image/Logo.png" alt="Logo" className="h-12 mr-4" />
            <div>
              <h1 className="text-3xl font-semibold text-gray-800">Skin Cancer Detection Report</h1>
              <p className="text-sm text-gray-600">Generated by our AI-powered system</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-sm text-gray-600">Date: {new Date().toLocaleDateString()}</p>
            <p className="text-sm text-gray-600">Report ID: {reportId}</p>
          </div>
        </header>
        
        {/* Report content goes here */}
        <div>
          <h2>Patient Name: {reportData.patientName}</h2>
          <p>Predicted Class: {reportData.predicted_class}</p>
          {/* Other report details */}
        </div>

        {/* Download PDF Button */}
        <button onClick={handleDownload} className="bg-blue-500 text-white px-4 py-2 rounded mt-4">
          Download Report
        </button>
      </div>
    </div>
  );
};

export default ReportPage;
